version: '3.8'
 
services:
  db:
    image: mysql:8.0.28-debian
    container_name: database-course
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./sql
        target: /data/sql        
        read_only: true

      - type: volume
        source: mysql-volume
        target: /var/lib/mysql

volumes:
  mysql-volume:
