version: '3'
 
services:
  db:
    image: mysql:8.0.28-debian
    container_name: database-course
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql